s3_lifecycle: support value '0' for transition_days
ansible-collections/community.aws pull request #1077
Opened 2022-04-19 19:45 UTC by fmenabe

##### SUMMARY
`s3_lifecycle` module does not support value *0* for **transition_days** parameter. 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
s3_lifecycle

##### ADDITIONAL INFORMATION
A lifecycle rule with *0* as **transition_days** allows to create a rule that will move objects with a delta of just few hours (if set to *1*, objects will be moved with a delta of 1d + few hours).

When the value *0* is set, the value is stripped from the query and we get an error that is hard to correlate with an "invalid"  value on this parameter (which is valid as *0* is an integer):

```
- name: Create s3 buckets lifecycle rules
  s3_lifecycle:
    ec2_url: "FIXME"
    region: "FIXME"
    aws_access_key: "FIXME"
    aws_secret_key: "FIXME"
    name: "FIXME"
    rule_id: "onezone"
    transitions:
    - transition_days: 0
      storage_class: "ONEZONE_IA"
    state: present
    status: enabled

fatal: [localhost]: FAILED! => {
    "boto3_version": "1.21.3",
    "botocore_version": "1.24.19",
    "changed": false,
    "error": {
        "code": "MalformedXML",
        "message": "Extra element Transition in interleave"
    },
    "lifecycle_configuration": {
        "Rules": [
            {
                "Filter": {
                    "Prefix": ""
                },
                "ID": "onezone",
                "Status": "Enabled",
                "Transitions": [
                    {
                        "StorageClass": "ONEZONE_IA"
                    }
                ]
            }
        ]
    },
    ...
MSG:

An error occurred (MalformedXML) when calling the PutBucketLifecycleConfiguration operation: Extra element Transition in interleave
```

This is because `transition.get('transition_days')` returns *0* which is considered as *False* on a condition (this patch just check if the value is defined; e.g. is not *None*).

2022-04-19 20:42 UTC, tremble requested changes
Thanks for taking the time to raise this PR.

The change looks good at first glance.  If possible please would you:
1. Add integration tests to [tests/integration/targets/s3_lifecycle/tasks/main.yml](https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/s3_lifecycle/tasks/main.yml)
2. Add a [changelog entry](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to)

2022-04-20 05:17 UTC, markuman commented on tests/integration/targets/s3_lifecycle/tasks/main.yml
> +        storage_class: onezone_ia
> An error occurred (InvalidArgument) when calling the PutBucketLifecycleConfiguration operation: 'Days' in Transition action must be greater than or equal to 30 for storageClass 'ONEZONE_IA'

you must use another storage class to test `transition_days: 0`. The same for the 2nd idempotency test.

2022-04-20 05:17 UTC, markuman commented on tests/integration/targets/s3_lifecycle/tasks/main.yml
> +        storage_class: onezone_ia
@fmenabe

2022-04-20 07:55 UTC, tremble approved these changes

2022-04-20 08:12 UTC, fmenabe commented
Tests still fail because standard_ia and onezone_ia expect a transition days greater than 30 days (server side). I was going to force push my PR another time to move the tests on glacier storage class but I see you approved the changes, so should I do it?

2022-04-20 08:14 UTC, markuman commented
> Tests still fail because standard_ia and onezone_ia expect a transition days greater than 30 days (server side). I was going to force push my PR another time to move the tests on glacier storage class but I see you approved the changes, so should I do it?

Simply move on in this PR :) it won't be merged as long as the ci is failing.

2022-04-20 08:25 UTC, tremble commented
> but I see you approved the changes, so should I do it?

The approval was to recognise that I'm happy with the code change and the changelog fragment.  Broken tests will need to be fixed.

2022-04-20 08:40 UTC, markuman approved these changes

2022-04-20 08:42 UTC, markuman commented
@fmenabe thank you for your contribution.

2022-04-20 08:51 UTC, fmenabe commented
@tremble @markuman thanks for your quick review and help!

No hurry for me but by curiosity, how much time does it take generally to go upstream?

2022-04-20 08:53 UTC, markuman commented
> @tremble @markuman thanks for your quick review and help!
> 
> No hurry for me but by curiosity, how much time does it take generally to go upstream?

there are no release dates yet: https://github.com/ansible-collections/community.aws/issues/890  
I guess something between 3 and 6 weeks.

2022-04-20 09:03 UTC, merged