lambda_info - Return list of dicts as opposed to dict of dicts
ansible-collections/community.aws pull request #1239
Opened 2022-06-14 21:02 UTC by jatorcasso

##### SUMMARY
- Previously returned `function`, which was a dict of dicts. Deprecated `function` in replace of `lambda_info` which is a list of dicts.
- Return config details regardless of query (function_arn, function_name, etc)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lambda_info

2022-06-15 07:52 UTC, tremble commented
This seems a little excessive, I was expecting more:

```
"lambda_info":
    [   
        {
            "aliases": [], 
            "code_sha256": "mUwWuD7qBnKT2Q8cAGEyvbZelDUy+1Z7MOoIK6e9lIU=",
            "code_size": 854,
            "description": "", 
            "function_arn": "arn:aws:lambda:us-east-1:721066863947:function:7abd55cd699e",
            "function_name": "7abd55cd699e",
            "handler": "mini_lambda.handler",
            "last_modified": "2022-06-14T19:17:53.620+0000",
            "mappings": [], 
            "memory_size": 128,
            "package_type": "Zip",
            "policy": {}, 
            "revision_id": "ba9a3e6e-7aa8-4568-ac78-0945db756a93",
            "role": "arn:aws:iam::721066863947:role/ansible-test-7abd55cd699e-lambda",
            "runtime": "python3.9",
            "state": "Pending",
            "state_reason": "The function is being created.",
            "state_reason_code": "Creating",
            "tags": {}, 
            "timeout": 3,
            "tracing_config": {
                "mode": "PassThrough"
            },  
            "version": "$LATEST",
            "versions": [
                {   
                    "code_sha256": "mUwWuD7qBnKT2Q8cAGEyvbZelDUy+1Z7MOoIK6e9lIU=",
                    "code_size": 854,
                    "description": "", 
                    "function_arn": "arn:aws:lambda:us-east-1:721066863947:function:7abd55cd699e:$LATEST",
                    "function_name": "7abd55cd699e",
                    "handler": "mini_lambda.handler",
                    "last_modified": "2022-06-14T19:17:53.620+0000",
                    "memory_size": 128,
                    "package_type": "Zip",
                    "revision_id": "ba9a3e6e-7aa8-4568-ac78-0945db756a93",
                    "role": "arn:aws:iam::721066863947:role/ansible-test-7abd55cd699e-lambda",
                    "runtime": "python3.9",
                    "timeout": 3,
                    "tracing_config": {
                        "mode": "PassThrough"
                    },
                    "version": "$LATEST"
                },
                {   
                    "code_sha256": "mUwWuD7qBnKT2Q8cAGEyvbZelDUy+1Z7MOoIK6e9lIU=",
                    "code_size": 854,
                    "description": "", 
                    "function_arn": "arn:aws:lambda:us-east-1:721066863947:function:7abd55cd699e:$LATEST",
                    "function_name": "7abd55cd699e",
                    "handler": "mini_lambda.handler",
                    "last_modified": "2022-06-14T19:17:53.620+0000",
                    "memory_size": 128,
                    "package_type": "Zip",
                    "revision_id": "ba9a3e6e-7aa8-4568-ac78-0945db756a93",
                    "role": "arn:aws:iam::721066863947:role/ansible-test-7abd55cd699e-lambda",
                    "runtime": "python3.9",
                    "timeout": 3,
                    "tracing_config": {
                        "mode": "PassThrough"
                    },
                    "version": "$LATEST"
                },
                {   
                    "code_sha256": "mUwWuD7qBnKT2Q8cAGEyvbZelDUy+1Z7MOoIK6e9lIU=",
                    "code_size": 854,
                    "description": "",
                    "function_arn": "arn:aws:lambda:us-east-1:721066863947:function:7abd55cd699e:1",
                    "function_name": "7abd55cd699e",
                    "handler": "mini_lambda.handler",
                    "last_modified": "2022-06-14T19:17:53.620+0000",
                    "memory_size": 128,
                    "package_type": "Zip",
                    "revision_id": "e9df78b3-ccd1-4319-8c44-ef53b8a7bb8d",
                    "role": "arn:aws:iam::721066863947:role/ansible-test-7abd55cd699e-lambda",
                    "runtime": "python3.9",
                    "timeout": 3,
                    "tracing_config": {
                        "mode": "PassThrough"
                    },
                    "version": "1"
                }
            ]
        }
    ],
"response_metadata": {
    ...
}
```

2022-06-15 13:24 UTC, jatorcasso commented
> This seems a little excessive, I was expecting more:

I agree. However, response metadata is returned for each lambda, so i'm not sure how we could do that. Unless we returned a list of response_metadatas

2022-06-28 16:33 UTC, tremble commented
recheck

2022-06-29 09:10 UTC, tremble requested changes

2022-06-29 09:10 UTC, tremble commented on changelogs/fragments/1239-lambda_info-return_list.yml
> +- lambda_info - add return key ``lambda_info`` which returns a list of dictionaries instead of the previously returned
Based on https://github.com/ansible-collections/amazon.aws/pull/865

This should probably be "functions" instead of "lambda_info"

2022-06-29 14:33 UTC, alinabuzachis approved these changes

2022-06-29 14:52 UTC, tremble commented on plugins/modules/lambda_info.py
> +        "The returned key 'function', which returned a dictionary of dictionaries, is deprecated and will be replaced by 'lambda_info',"
```suggestion
        "The returned key 'function', which returned a dictionary of dictionaries, is deprecated and will be replaced by 'functions',"
```

2022-06-29 17:34 UTC, tremble approved these changes

2022-06-29 20:31 UTC, merged