Fix SASL/SCRAM + add option for SASL IAM & add option to disable unauthenticated clients
ansible-collections/community.aws pull request #1764
Opened 2023-03-30 14:33 UTC by eRadical

##### SUMMARY
- fix SASL/SCRAM - Fixes #1761 
- add IAM authentication
- add option to disable unauthenticated clients

Many thanx to @markuman for throwing me into this issue.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
msk_cluster

##### ADDITIONAL INFORMATION
I will probably add more tests after working w/ this.

2023-03-30 15:06 UTC, tremble commented
@eRadical I see you fighting with the formatting/darker stuff

If you install "darker" ( https://pypi.org/project/darker/ ) it should be possible to just run the darker command in the `community/aws/` directory and it'll apply all the formatting for you (including some of the tweaks we have, like line length)

2023-03-30 15:23 UTC, tremble requested changes
Many thanks for this.

Down at line 695 there's a "module_args" parameter, this will also need to be updated, the DOCUMENTATION fragment is only documentation (upstream Ansible is aware that this isn't the greatest, but changing this for modules is non-trivial)

Does it make sense for all of these new options to have default values?  Will they conflict with each other?  it might make more sense for 
```
msk_cluster:
   ...
   authentication: {}
   ...
```

To be the way to disable authentication, rather than an explicitly parameter (especially one with a default value.

2023-03-30 15:23 UTC, tremble commented on plugins/modules/msk_cluster.py
> +                default: False
```suggestion
                default: False
                version_added: 5.5.0
```

2023-03-30 15:58 UTC, eRadical commented on changelogs/fragments/1761-msk_cluster-fix-authentication.yml
> +- msk_cluster - fix creating a cluster w/ sasl_scram authentication (https://github.com/ansible-collections/community.aws/issues/1761).
will do

2023-03-30 16:09 UTC, eRadical commented
> To be the way to disable authentication, rather than an explicitly parameter (especially one with a default value.

You need to explicitly disable "Unauthenticated access".

It looks like this:
![image](https://user-images.githubusercontent.com/70473/228898140-942f90aa-3ad5-4e82-b568-7acc985b7d71.png)

As you can see there are 4 independed checkboxes.

2023-03-30 18:16 UTC, markuman commented
> When I created a cluster w/ Ansible it created only w/ "Unauthenticated" checked. So I suspect the boto default is actually "Unauthenticated".

For us it is the default then. Otherwise it would break backwards compatibility.

2023-03-30 18:46 UTC, markuman commented on plugins/modules/msk_cluster.py
> +                description: Option to explicitly turn on or off authentication
```suggestion
                description: Option to explicitly turn on or off authentication
```

2023-03-30 18:51 UTC, markuman commented on plugins/modules/msk_cluster.py
> +                default: True
```suggestion
            unauthenticated:
                version_added: 5.5.0
                description: Option to explicitly turn on or off authentication
                type: bool
                default: True
```

2023-03-30 18:53 UTC, markuman commented
> ERROR: plugins/modules/msk_cluster.py:132:80: W291: trailing whitespace

 is fixed and committed.

> ERROR: plugins/modules/msk_cluster.py:0:0: doc-default-does-not-match-spec: Argument 'sasl_iam' in argument_spec found in authentication defines default as (None) but documentation defines default as (False)
> ERROR: plugins/modules/msk_cluster.py:0:0: doc-default-does-not-match-spec: Argument 'unauthenticated' in argument_spec found in authentication defines default as (None) but documentation defines default as (True)

```diff
diff --git a/plugins/modules/msk_cluster.py b/plugins/modules/msk_cluster.py
index 31e2fe6a..46681d95 100644
--- a/plugins/modules/msk_cluster.py
+++ b/plugins/modules/msk_cluster.py
@@ -126,12 +126,10 @@ options:
             sasl_iam:
                 description: IAM authentication is enabled or not.
                 type: bool
-                default: False
                 version_added: 5.5.0
             unauthenticated:
                 description: Option to explicitly turn on or off authentication
                 type: bool
-                default: True
     enhanced_monitoring:
         description: Specifies the level of monitoring for the MSK cluster.
         choices:

```

sanity is surviving here locally. `ansible-test sanity  --python 3.10 plugins/modules/msk_cluster.py --docker default`  
but I haven't look deeper in the logic.

As mentioned above, we must keep backwards compatibility. So the module must result in the same settings, when those parameters are not set on execution.

2023-03-31 15:03 UTC, eRadical commented
@markuman 

Can I do default & required?

```
    authentication:
        description:
            - Includes all client authentication related information.
            - Effective only for new cluster and can not be updated.
        type: dict
        suboptions:
            tls_ca_arn:
                description: List of ACM Certificate Authority ARNs.
                type: list
                elements: str
                default: False
                required: False
            sasl_scram:
                description: SASL/SCRAM authentication is enabled or not.
                type: bool
                default: False
                required: False
            sasl_iam:
                description: IAM authentication is enabled or not.
                type: bool
                default: False
                required: False
                version_added: 5.5.0
            unauthenticated:
                version_added: 5.5.0
                description: Option to explicitly turn on or off authentication
                type: bool
                default: True
                required: False
```
Note in `unauthenticated` that default is True and not required :)

2023-03-31 15:13 UTC, eRadical commented
Nvm, I just did a push, let's see how it goes!

2023-03-31 16:46 UTC, markuman commented
recheck

2023-03-31 18:37 UTC, markuman commented
hm, maybe the entire msk test takes to long now. Any ideas @tremble?

2023-03-31 19:26 UTC, eRadical commented
Yes, it might be. As they are now: tests are starting and stopping 4 clusters:
- old usual test,
- sasl_scram,
- sasl_iam,
- a cluster w/ sasl_scram  but `unauthenticated` disabled.

For me it takes about 1h to do a cluster change (switch unauthenticated to off or add sasl_iam).
I'll merge all the other tests into one tomorrow.

2023-04-01 07:09 UTC, eRadical commented
Done!
I've also rebased.

2023-04-01 08:19 UTC, eRadical commented
```
2023-04-01 08:10:33.996790 \| controller \| TASK [msk_cluster : update msk cluster] ****************************************
--
5100 | 2023-04-01 08:10:33.996795 \| controller \| task path: /home/zuul-worker/.ansible/collections/ansible_collections/community/aws/tests/integration/targets/msk_cluster/tasks/test_update.yml:24
5101 | 2023-04-01 08:12:10.438294 \| RUN END RESULT_TIMED_OUT: [untrusted : github.com/ansible/ansible-zuul-jobs/playbooks/ansible-test-base/run.yaml@master]
```

It times out at update so we're not reaching the second cluster, not even cluster deletion.

2023-04-03 07:41 UTC, markuman commented
> It times out at update so we're not reaching the second cluster, not even cluster deletion.

cluster deletion is handled in that case the [aws-terminator](https://github.com/mattclay/aws-terminator).  

@tremble any ideas?

2023-04-04 19:42 UTC, markuman commented
> hm, maybe the entire msk test takes to long now. Any ideas @tremble?

@goneri any ideas here?

2023-04-05 14:34 UTC, eRadical commented
Same timeout.

(I pretty sure we can increase the timeout.)
Should we increase timeout?

2023-04-18 11:58 UTC, markuman commented
recheck

2023-04-18 16:40 UTC, markuman commented
> 2023-04-18 13:48:04.265593 | controller | botocore.errorfactory.ConflictException: An error occurred (ConflictException) when calling the CreateConfiguration operation: A resource with this name already exists.

Unclear for me if just the integration test has a bug or if this is a side effect by splitting the test.  
Any thoughts about it @tremble @eRadical?

2023-04-18 18:36 UTC, eRadical commented
I'll test tomorrow in the office as I also need to start the prod clusters.

2023-04-19 07:30 UTC, tremble commented
> > 2023-04-18 13:48:04.265593 | controller | botocore.errorfactory.ConflictException: An error occurred (ConflictException) when calling the CreateConfiguration operation: A resource with this name already exists.
> 
> Unclear for me if just the integration test has a bug or if this is a side effect by splitting the test. Any thoughts about it @tremble @eRadical?

The actual failure is:
```
2023-04-18 13:46:43.316236 | controller | TASK [msk_cluster-auth : validate return values] *******************************
2023-04-18 13:46:43.316241 | controller | task path: /home/zuul-worker/.ansible/collections/ansible_collections/community/aws/tests/integration/targets/msk_cluster-auth/tasks/test_create_auth.yml:49
2023-04-18 13:46:43.398248 | controller | fatal: [testhost]: FAILED! => {
2023-04-18 13:46:43.398293 | controller |     "msg": "The conditional check 'msk_cluster.cluster_info.client_authentication.sasl.scram.enabled == true' failed. The error was: error while evaluating conditional (msk_cluster.cluster_info.client_authentication.sasl.scram.enabled == true): 'dict object' has no attribute 'scram'. 'dict object' has no attribute 'scram'"
2023-04-18 13:46:43.398300 | controller | }
```

The cluster is then being left in the "deleting" state, and when it's retried (with added verbosity) it fails because the deletion hadn't completed.

2023-04-19 08:47 UTC, tremble commented
@eRadical it looks like the failing test was caused by a combination of 2 things:
- AWS APIs not always returning disabled options (eg Unauthenticated)
- Enabling "Iam" auth was replacing enabling "SCRAM" auth

2023-04-19 09:44 UTC, tremble approved these changes
Note: for 5.5 we'll need to explicitly bump and test for the botocore versions

2023-04-19 10:38 UTC, tremble commented
regate

2023-04-19 11:42 UTC, merged

2023-04-19 13:24 UTC, tremble commented
@eRadical,

Thanks for your work on this.  Your work should be available when we release 5.5.0.  This is expected within the next couple of weeks (along with 6.0.0)

2023-04-20 11:28 UTC, eRadical commented
@tremble - It was my pleasure! ...and (I think) also the normal path after working & promoting Ansible for a long time. I just hope it's just the beginning.