dynamodb_table: secondary indexes are now created
ansible-collections/community.aws pull request #1826
Opened 2023-05-25 15:52 UTC by gsimon75

##### SUMMARY

Fixes: #1825 

Possibly by a typo, the index definition being checked was over-defined by an empty dict [here](https://github.com/ansible-collections/community.aws/blob/e80bf933412ea5c7ab2a94af945170cb2ebd900f/plugins/modules/dynamodb_table.py#L678).
Without that line the index processing proceeds fine.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
`dynamodb_table`

2023-05-25 15:56 UTC, tremble requested changes
The change looks reasonable.

If possible please could you add an integration test to https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/dynamodb_table/tasks/main.yml this helps to avoid accidental regressions

2023-05-25 15:56 UTC, tremble commented on changelogs/fragments/1825-dynamodb-table-no-secondary-indexes.yml
> +  - dynamodb_table - secondary indexes are now created
```suggestion
  - dynamodb_table - secondary indexes are now created (https://github.com/ansible-collections/community.aws/issues/1825).
```

2023-05-25 17:07 UTC, gsimon75 commented
I've committed an attempt at the test cases, but I had some troubles testing them locally, it may not be the final version :)

2023-05-26 06:46 UTC, markuman commented
Task

> TASK [dynamodb_table : Create table with composite PK] 

is failing with error message

> "msg": "DynamoDB does not support updating the Primary keys on a table. Changed paramters are: ['range_key_name', 'range_key_type']",

I am not familar with dynamodb. I'm not sure if the error exists before this PR or not.

2023-05-26 07:59 UTC, gsimon75 commented
> > TASK [dynamodb_table : Create table with composite PK]
> > "msg": "DynamoDB does not support updating the Primary keys on a table. Changed paramters are: ['range_key_name', 'range_key_type']", 
>  I'm not sure if the error exists before this PR or not.

No, it's one of the new test cases I'm adding, and most probably I've mis-typed something, like haven't marked a (negative) test as expected-to-fail. I'm on it :) ...

2023-06-01 04:16 UTC, markuman approved these changes

2023-06-01 07:15 UTC, tremble approved these changes
Thanks for adding the tests.

2023-06-01 10:40 UTC, gsimon75 commented
According to the [logs](https://ansible.softwarefactory-project.io/zuul/build/a55403215caf4b789121bf4053cc41d3):
```
TASK [dynamodb_table : Update table add indexes] *******************************
task path: /home/zuul/.ansible/collections/ansible_collections/community/aws/tests/integration/targets/dynamodb_table/tasks/main.yml:700
...
botocore.errorfactory.LimitExceededException: An error occurred (LimitExceededException) when calling the UpdateTable operation: Subscriber limit exceeded: Only 1 online index can be created or deleted simultaneously per table
```

It's sort of strange, as that this `name: "{{ table_name }}"` table gets its indexes first time [at the failing task](https://github.com/gsimon75/community.aws/blob/08ca4eede494d88a283ed1ba527e7dc14cd0cca3/tests/integration/targets/dynamodb_table/tasks/main.yml#L704)...

2023-06-01 13:04 UTC, markuman commented
regate

2023-06-01 15:30 UTC, gsimon75 commented
Same task, different error:
```
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the UpdateTable operation: Requested resource not found: Table: ansible-test-40302627-np0003872128 not found
```

Just a hunch, but it seems like two different tests are meddling with the table in parallel: while this test wants to create the table then add indexes then destroy the table, there seems to be another one which interferes with it.
When the other gets to creating the indices first, we get the previous LimitExceededException. When it gets to deleting the table first, we get this ResourceNotFoundException.

Do you think it has any possibility to be the case here?

2023-06-08 08:14 UTC, alinabuzachis commented
regate

2023-06-08 09:26 UTC, merged