fix(connection): get bucket_region in aws_ssm
ansible-collections/community.aws pull request #1908
Opened 2023-08-08 01:01 UTC by Hokwang

##### SUMMARY

when bucket is in us-east-1,
`bucket_location["LocationConstraint"]` is null

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
connection

##### ADDITIONAL INFORMATION

add condition for `bucket_region`

2023-08-30 17:48 UTC, 0xalex88 commented
Is it possible for anyone to review this?
I've encountered the same issue and it took a while to figure out.
In our case the aws client is set to us-west-2 but we're running a playbook on instances in multiple regions (and each of the hosts has ansible_aws_ssm_region correctly set).

2024-01-10 10:27 UTC, tremble requested changes
Thanks for taking the time to submit this PR, please add a changelog fragment:

https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

2024-01-11 08:21 UTC, tremble approved these changes

2024-01-11 08:21 UTC, tremble commented on changelogs/fragments/1908-fix_find_out_bucket_region_logic.yml
> +  - ssm(connection) - fix find out bucket region logic when region is us-east-1, us-east-1 region bucket_location["LocationConstraint"] is null
```suggestion
  - ssm(connection) - fix bucket region logic when region is ``us-east-1`` (https://github.com/ansible-collections/community.aws/pull/1908)
```

2024-01-11 08:54 UTC, merged