Promote iam_group module
ansible-collections/community.aws pull request #1945
Opened 2023-09-13 19:44 UTC by mandar242

##### SUMMARY

- Remove iam_group modules and tests
-These modules have been migrated to amazon.aws
- Update runtime.yml with redirects to that collection
- Update ignore files

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-09-14 07:20 UTC, tremble requested changes
Again, runtime.yml indentation changed, old "main"?

2023-09-14 20:28 UTC, hakbailey commented on changelogs/fragments/migrate_iam_group.yml
> +  to use ``community.aws.iam_group``.
I think this needs to be changed here too.

2023-09-15 06:31 UTC, tremble approved these changes

2023-09-15 13:40 UTC, abikouo approved these changes

2023-09-15 19:54 UTC, hakbailey approved these changes

2023-09-19 14:38 UTC, alinabuzachis approved these changes

2023-09-19 17:12 UTC, mandar242 commented
recheck

2023-09-20 16:25 UTC, merged