Prep amazon.aws 7.0.0 release
ansible-collections/community.aws pull request #1992
Opened 2023-11-02 15:04 UTC by alinabuzachis

##### SUMMARY

Prep amazon.aws 7.0.0 release

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

several

2023-11-02 15:07 UTC, alinabuzachis commented
Close and re-open to trigger github workflows.

2023-11-02 15:20 UTC, alinabuzachis commented
It is failing because this one has not been merged yet https://github.com/ansible-collections/amazon.aws/pull/1837

2023-11-02 15:22 UTC, alinabuzachis commented
@tremble do we want to wait until https://github.com/ansible-collections/amazon.aws/pull/1837 is merged or keep amazon.aws: '>=7.0.0-dev0' as dependency?

2023-11-02 15:33 UTC, tremble requested changes

2023-11-02 15:33 UTC, tremble commented on galaxy.yml
> +  amazon.aws: '>=8.0.0-dev0'
```suggestion
  amazon.aws: '>=7.0.0'
```

This is still the stable-7 branch, we only need amazon.aws 7.x :)

`>= 8.0.0-dev0` will be needed on the `main` branch, but can't be done without https://github.com/ansible-collections/amazon.aws/pull/1837

2023-11-02 15:33 UTC, tremble approved these changes

2023-11-02 22:03 UTC, alinabuzachis commented
recheck

2023-11-03 10:24 UTC, alinabuzachis commented
recheck

2023-11-06 15:22 UTC, merged