add support for G.4X and G.8X in glue_job.py
ansible-collections/community.aws pull request #2048
Opened 2024-01-19 14:49 UTC by randomnaja

##### SUMMARY
according to https://aws.amazon.com/about-aws/whats-new/2023/05/aws-glue-large-instance-types-generally-available/ I added support for these 2 new instance types

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
glue_job

2024-01-30 08:38 UTC, tremble requested changes
Thanks for taking the time to submit this PR.

Please add a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy

2024-01-30 08:38 UTC, tremble commented on plugins/modules/glue_job.py
> +      - new instance types G.4X and G.8X [https://aws.amazon.com/about-aws/whats-new/2023/05/aws-glue-large-instance-types-generally-available/]
```suggestion
      - Support for instance types C(G.4X( and C(G.8X) was added in community.aws release 7.2.0.
```

2024-02-21 00:53 UTC, randomnaja commented
> Thanks for taking the time to submit this PR.
> 
> Please add a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy

I added changelog fragment

2024-03-01 18:00 UTC, alinabuzachis approved these changes

2024-03-04 07:33 UTC, tremble approved these changes

2024-03-04 07:33 UTC, tremble commented on changelogs/fragments/2048-add-new-instance-types-in-gluejob.yaml
> +  - glue_job - add support for 2 new instance types which are G.4X and G.8X
```suggestion
  - glue_job - add support for 2 new instance types which are G.4X and G.8X (https://github.com/ansible-collections/community.aws/pull/2048).
```

2024-03-25 00:33 UTC, randomnaja commented
Is there any progress on merging this PR ?

2024-03-25 08:49 UTC, merged