fixes ec2_transit_gateway bug with empty description.
ansible-collections/community.aws pull request #2086
Opened 2024-05-07 20:16 UTC by paulczar

##### SUMMARY

When one or more TGWs exist with an empty description, the module will fail.

Fixes #1893

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ec2_transit_gateway

2024-05-07 20:25 UTC, branic approved these changes
This looks good to me.

2024-05-08 08:46 UTC, tremble requested changes
Many thanks for this @paulczar and @branic (for reviewing).

Please could you add a changelog fragment https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

2024-09-23 14:55 UTC, GomathiselviS commented
Hi @paulczar I have pushed the changelog fragment. Once approved, I shall merge this PR.

2024-09-25 12:48 UTC, alinabuzachis approved these changes

2024-11-05 16:26 UTC, gravesm commented
Closing this PR as the transit gateway module was migrated to amazon.aws. The PR has been reissued in https://github.com/ansible-collections/amazon.aws/pull/2375

2024-11-05 16:26 UTC, closed without merging