Support min max object size in s3_lifecycle module
ansible-collections/community.aws pull request #2205
Opened 2024-12-17 23:43 UTC by leo4ever

##### SUMMARY

Support the S3 lifecycle settings of minimum and maximum object size to apply the lifecycle rules.

Fixes #861

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

s3_lifecycle

##### ADDITIONAL INFORMATION

```paste below

```

2024-12-18 14:07 UTC, tremble requested changes
Thanks for taking the time to submit this, especially for including the new integration tests.

If you take a look at the output from the tests you'll see a couple of issues:

- https://github.com/ansible-collections/community.aws/actions/runs/12383415807job/34597832812?pr=2205
- https://github.com/ansible-collections/community.aws/actions/runs/12383415807/job/34597834846?pr=2205

These boil down to

- The typo on line 1 breaks the documentation (YAML)
- We use the "black" formatting style, If you've got tox setup, then `tox -m format`  it should fix the formatting.

WRT Unit tests:
Unit tests can be a PITA to implement (they live under tests/unit/plugins/modules/).
I'd really like to see some basic tests for filters_are_equal if possible.  However, by moving filters_are_equal outside of compare_and_update_configuration you'll make it easier for someone (possibly me) to come along later and add them if you're not able to do so.

2024-12-19 00:07 UTC, leo4ever commented on plugins/modules/s3_lifecycle.py
> +    descriptionL
@tremble - I have made the changes based on your comments. But still seeing the build on collections docs failing - https://github.com/ansible-collections/community.aws/actions/runs/12403295884

I have created a unit test but having trouble trying to run tests locally. Can this test be executed as part of CI?

2024-12-22 14:52 UTC, tremble commented on plugins/modules/s3_lifecycle.py
> +        minimum_object_size=dict(type=int),
```suggestion
        maximum_object_size=dict(type="int"),
        minimum_object_size=dict(type="int"),
```

2024-12-23 10:00 UTC, tremble commented
One other minor request:  Please add a "minor_changes" changelog entry: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

2024-12-28 10:42 UTC, tremble approved these changes
Thanks,

Just as an FYI, you're still falling foul of some of our linting checks (`tox -m lint`), however they're all whitespace related so I'll push fixes.

For the unit tests, rather than quite so much copy and paste it's also possible to use pytest's `parameterize` which creates lots of copy&paste versions of the tests and means that if they start failing, it'll list all of the failed tests rather than just one.

2024-12-28 10:42 UTC, tremble commented on changelogs/fragments/2205-support-minmax-s3lifecycle.yml
> +  - s3_lifecycle - Support for min and max object size when applying the filter rules.
```suggestion
  - s3_lifecycle - Support for min and max object size when applying the filter rules (https://github.com/ansible-collections/community.aws/pull/2205).
```

2024-12-28 10:42 UTC, tremble commented on plugins/modules/s3_lifecycle.py
> +    type: int
```suggestion
    type: int
    version_added: 9.1.0
```

2024-12-28 10:42 UTC, tremble commented on plugins/modules/s3_lifecycle.py
> +    required: false
```suggestion
    required: false
    version_added: 9.1.0
```

2024-12-28 10:42 UTC, tremble commented on plugins/modules/s3_lifecycle.py
> +# Helper function to deeply compare filters
```suggestion

# Helper function to deeply compare filters
```

2024-12-28 10:42 UTC, tremble commented on plugins/modules/s3_lifecycle.py
> +
```suggestion


```

2024-12-28 10:42 UTC, tremble commented on plugins/modules/s3_lifecycle.py
> +
```suggestion

```

2024-12-28 10:42 UTC, tremble commented on plugins/modules/s3_lifecycle.py
> +    main()
```suggestion
    main()
```

2024-12-28 10:42 UTC, tremble commented on tests/unit/plugins/modules/test_s3_lifecycle_filters_are_equal.py
> +
```suggestion


```

2024-12-28 10:42 UTC, tremble commented on tests/unit/plugins/modules/test_s3_lifecycle_filters_are_equal.py
> +            "Prefix": "nested/", # Different key/value
```suggestion
            "Prefix": "nested/",  # Different key/value
```

2024-12-28 10:42 UTC, tremble commented on tests/unit/plugins/modules/test_s3_lifecycle_filters_are_equal.py
> +    assert filters_are_equal(filter1, filter2) is True
```suggestion
    assert filters_are_equal(filter1, filter2) is True
```

2024-12-28 10:42 UTC, tremble commented on tests/unit/plugins/modules/test_s3_lifecycle_filters_are_equal.py
> +            "ObjectSizeLessThan": 150,
```suggestion
            "ObjectSizeLessThan": 150,
```

2024-12-29 10:57 UTC, merged