Type conversion issue for creating read replicas
ansible-collections/community.aws pull request #229
Opened 2020-09-16 15:27 UTC by tombenninger

##### SUMMARY

When create_db_instance is called, it converts the dict to a tag list, but this is not happening when create_db_instance_read_replica is called, which causes:
```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Tags, value: **TAGS LISTED HERE**, type: <class 'dict'>, valid types: <class 'list'>, <class 'tuple'>
```
This patch just calls the same date type conversion in both cases.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
modules/cloud/amazon/rds_instance.py

##### ADDITIONAL INFORMATION
Steps to reproduce:

1. Create a postgres RDS instance, with tags using the module.
2. Create second read_replica RDS instance using the module.

2020-09-16 15:38 UTC, tremble requested changes
Thanks for taking the time to submit this pull request.  It looks like the tests are currently not running in CI so I'll need to poke about a bit to get the test suite running.

In the mean time please could you
- add a changelog fragment:  https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to
- update the test suite to include tags in the [read_replica tests
](https://github.com/ansible-collections/community.aws/blob/main/tests/integration/targets/rds_instance/tasks/test_read_replica.yml) to help reduce the chance of a regression.

2020-09-17 00:51 UTC, tombenninger commented
The latest errors on Shippable all seem to be related to issues with the tool timing out trying to connect to other resources. Should I push a no-op change to re-run testing?

2020-09-17 07:37 UTC, tremble commented
Currently there's a couple of options for retrying flakes:

- Find a friendly collection maintainer (mostly lurking in #ansible-aws on Freenode)
- Rebase and force push (I sometimes tweak the order of commit, squash/fixup minor commits, tweak a commit message, etc)
- push an empty commit
- close and reopen (gets a little spammy)

Once we've got the bot consistently running you'll be able to ask it to retry failed CI runs: https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#commands

2020-09-25 12:50 UTC, tremble approved these changes
Tests in place and passing.  Change looks sane.  Merging.

2020-09-25 12:50 UTC, merged

2020-09-25 12:51 UTC, tremble commented
Thanks for your submission @tombenninger.