Fully support mixed instance policy
ansible-collections/community.aws pull request #232
Opened 2020-09-16 16:46 UTC by JacobHenner

##### SUMMARY

Previously, setting instances_distribution was not supported.
instances_distribution should be supported, to allow users to enable
spot instances within their mixed instance ASGs.

Note: The type and significance of the mixed_instance_policy has
changed. It now captures all of the mixed_instance_policy configuration
parameters, rather than just a list of instance types.

Fixes #231

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ec2_asg

2020-09-16 16:48 UTC, JacobHenner commented
I just realized tests were not updated - handling that now.

2020-09-16 17:35 UTC, JacobHenner commented
It looks like some shippable tests have failed due to issues pulling docker images.

2020-09-17 09:19 UTC, tremble requested changes
Thanks for taking the time to submit this change.  I've retriggered the failed CI tests and they're now passing.

Mostly nits:

- Please add some additional tasks to the integration tests rather than updating the existing tasks: it's important that we know that the existing behaviour doesn't change and break as people move between versions.
- Please add a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to
- Unfortunately I think we need to use a different name for the new return data, switching from a list to a dict will break existing playbooks.  (full_mixed_instances_policy ?)  (@jillr @garethr any opinions?)

2020-09-17 18:20 UTC, JacobHenner commented
Thanks for the feedback. I'll make the requested adjustments either later today or tomorrow.

2020-09-21 17:06 UTC, JacobHenner commented on plugins/modules/ec2_asg.py
> +    type: dict
Changes made in response to feedback

2020-10-15 08:11 UTC, markuman approved these changes
LGTM

2020-10-15 08:12 UTC, markuman commented
@JacobHenner can you resolve the change requst by @tremble?

2020-10-15 08:31 UTC, tremble approved these changes
The code looks sound.  I'd like @jillr or @s-hertel to have a quick look and do the merge if they're happy with the formatting.

2020-10-15 08:31 UTC, tremble commented on plugins/modules/ec2_asg.py
> +                instances_distribution_params = dict(
I personally find this flow/formatting a little harder to follow than it should be.

Tests show that the code works, and I know that this is a valid pythonic way to do this.  As such I'll put my +1 but I'd like to have @jillr's opinion if there's a better way to format this before we merge

2020-10-22 23:17 UTC, jillr reviewed
The code looks good but I haven't been able to test successfully, #230 is breaking the test suite and I haven't sorted that out yet. @tremble were you able to test this change?

2021-02-12 20:25 UTC, goneri commented
@JacobHenner, don't be surprised, I rebased your PR :-).

2021-02-12 21:36 UTC, jillr reviewed
Apologies this one stalled @JacobHenner, I think we just need to add back the import for camel_dict_to_snake_dict (I suspect it was removed in another commit now that this PR has been rebased). That should get the sanity tests passing so that we can merge.

2021-02-13 13:00 UTC, tremble requested changes
A few minor bits and pieces.  Let's see if we can get this over the finishing line

2021-02-13 16:21 UTC, tremble approved these changes
Ran the tests locally.  ec2_launch_template is currently broken but once fixed the unsupported ec2_asg tests pass with this change.

2021-03-31 10:48 UTC, tremble approved these changes
Noticed some missing version_added.

2021-03-31 10:48 UTC, tremble commented on plugins/modules/ec2_asg.py
> +        type: dict
```suggestion
        type: dict
        version_added: 1.5.0
```

2021-03-31 10:48 UTC, tremble commented on plugins/modules/ec2_asg.py
> +            required: false
```suggestion
            required: false
            version_added: 1.5.0
```

2021-03-31 10:48 UTC, tremble commented on plugins/modules/ec2_asg.py
> +            required: false
```suggestion
            required: false
            version_added: 1.5.0
```

2021-03-31 10:48 UTC, tremble commented on plugins/modules/ec2_asg.py
> +            required: false
```suggestion
            required: false
            version_added: 1.5.0
```

2021-03-31 10:48 UTC, tremble commented on plugins/modules/ec2_asg.py
> +            required: false
```suggestion
            required: false
            version_added: 1.5.0
```

2021-03-31 10:48 UTC, tremble commented on plugins/modules/ec2_asg.py
> +            required: false
```suggestion
            required: false
            version_added: 1.5.0
```

2021-03-31 10:48 UTC, tremble commented on plugins/modules/ec2_asg.py
> +            required: false
```suggestion
            required: false
            version_added: 1.5.0
```

2021-03-31 19:33 UTC, merged