Fix container param typing
ansible-collections/community.aws pull request #249
Opened 2020-10-01 01:22 UTC by cThrice

##### SUMMARY

The container param was incorrectly set as a STR.  Updated to correct type of DICT.
Additionally added some additional text to docs to assist in finding potential container options

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ecs_taskdefinition

##### ADDITIONAL INFORMATION

```
- name: Deploy taskdef
  hosts: localhost
  tasks:
    - name: Create task definition
      run_once: true
      ecs_taskdefinition:
        force_create: true
        family: nginx
        state: present
        launch_type: FARGATE
        cpu: 2048
        memory: 4096
        network_mode: awsvpc
        containers:
          - name: nginx
            essential: true
            image: "nginx"
```

```An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'str' object has no attribute 'get'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error

MODULE_STDERR:

Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/ky/_q58mhx922v_6h35pl4p57bc0000gn/T/ansible_ecs_taskdefinition_payload_7kb3qm_a/ansible_ecs_taskdefinition_payload.zip/ansible_collections/community/aws/plugins/modules/ecs_taskdefinition.py", line 517, in <module>
  File "/var/folders/ky/_q58mhx922v_6h35pl4p57bc0000gn/T/ansible_ecs_taskdefinition_payload_7kb3qm_a/ansible_ecs_taskdefinition_payload.zip/ansible_collections/community/aws/plugins/modules/ecs_taskdefinition.py", line 353, in main
AttributeError: 'str' object has no attribute 'get'

```

After applying fix, error resolved and taskdef was corrected successfully

2020-10-21 09:42 UTC, tremble requested changes
Hi, thanks for taking the time to submit this PR.

A couple of things:
- please could you add a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to
- Given the huge number of potential options for containers, I think it's reasonable to refer to the boto3 docs for the potential options.  However, I'd rather we gave folks a bit of a helping hand in finding them.

It looks like the reason this one slipped through is that the tests are currently disabled

2020-11-04 07:59 UTC, Surgo commented
@cThrice Would it be okay to fix in #238?

2020-11-27 06:56 UTC, Surgo commented on plugins/modules/ecs_taskdefinition.py
> +            - A list of containers definitions.  You can find the full list of options in the boto3 docs.
Update docs in #238

2021-02-19 20:06 UTC, goneri commented
This issue should be fixed by https://github.com/ansible-collections/community.aws/pull/284. @cThrice can you check it works for you (main branch or 1.3.0 or greater)?

2021-02-19 20:06 UTC, closed without merging