Add _get_boto_client and STS token management.
ansible-collections/community.aws pull request #25
Opened 2020-04-06 17:27 UTC by flavioelawi

##### SUMMARY

Fixes #24 

Add the following parameters to aws_ssm.py connection plugin:
* ansible_aws_ssm_access_key_id
* ansible_aws_ssm_secret_access_key
* ansible_aws_ssm_session_token
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

This implements some basic STS token management, that can be passed as parameters to the task when the aws_ssm connection plugin is involved, the parameters are scoped to the plugin namespace.

##### ADDITIONAL INFORMATION

If you have a role that you allowed to assume in a target account, you would need to assume such role in the target account before invoking the task; this example comes from an invocation by using ansible APIs, where even assuming the role in the target account, the connection plugin was still executing under the controller-node account session.
```paste below
flavioel/.virtualenvs/ansible_ssm/lib/python3.6/site-packages/botocore/client.py\", line 626, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactor
y.TargetNotConnected: An error occurred (TargetNotConnected) when calling the StartSession operation: i-01234567890123456 is not connected.\n",
```
By implementing the changes in this PR I am able to pass an STS token as a parameter to the task, letting it execute under the target account context.

This change also allows for backward compatibility as if nothing is specified (no OS environment variables, no parameters) the boto3 client will automatically select the `default` profile configured on the controller.

2020-04-08 17:00 UTC, flavioelawi commented
Pinging the the plugin authors: @psharkey @hanumantharaomvl @gau1991 :)

2020-09-01 02:01 UTC, MrBones757 commented
Is there any update on when we might expect this change to be merged into stable?
It was originally discussed here: https://github.com/ansible/ansible/pull/49652#issuecomment-569858069
but it was never included in the final release.

Thanks for the PR though - saved me some time as i've just come across this issue myself!

2020-09-01 04:08 UTC, gau1991 approved these changes

2020-09-01 12:12 UTC, tremble approved these changes
Change looks sound, after a little digging my previous comments don't really hold true.  @gau1991 (one of the authors) has +1ed so I think we're good to merge this.

2020-09-01 12:20 UTC, tremble requested changes
Actually, two minor documentation things:
1. Please add a changelog fragment https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to
2. We need a `version_added` entry on the new options.

2020-09-01 12:20 UTC, tremble commented on plugins/connection/aws_ssm.py
> +    - name: ansible_aws_ssm_session_token
```suggestion
  access_key_id:
    description: The STS access key to use when connecting via session-manager.
    vars:
    - name: ansible_aws_ssm_access_key_id
    version_added: 1.3.0
  secret_access_key:
    description: The STS secret key to use when connecting via session-manager.
    vars:
    - name: ansible_aws_ssm_secret_access_key
    version_added: 1.3.0
  session_token:
    description: The STS session token to use when connecting via session-manager.
    vars:
    - name: ansible_aws_ssm_session_token
    version_added: 1.3.0
```

2020-09-01 19:57 UTC, flavioelawi commented
Cool, i'll squash the commits, add the changelog fragment and update the pr, thanks.

2020-09-01 20:11 UTC, closed without merging

2020-09-01 20:14 UTC, flavioelawi commented
I made a mess with the pull requests, the correct one is https://github.com/ansible-collections/community.aws/pull/218

sorry about that.