[BUG_FIX] ec2_win_password issue.
ansible-collections/community.aws pull request #283
Opened 2020-10-29 10:33 UTC by nikhilpatne

##### SUMMARY
Fixed  #142 and #145 
- ec2_win_password returns success when it fails to decode the password.
-  ec2_win_password returns changed state but doesn't change anything.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ec2_win_password

2020-11-03 06:14 UTC, nikhilpatne commented
Please someone review this PR..!!

2020-11-06 12:23 UTC, nikhilpatne commented
Please someone take a look on this PR..!!

2020-11-06 12:29 UTC, tremble commented
CC: @rickmendes (Author of the module) and @phospi

2020-11-06 13:45 UTC, phospi commented
LGTM. Do we need a change fragment?
[Creating a changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment)

2020-11-06 14:24 UTC, rickmendes approved these changes
LGTM

2020-11-09 12:08 UTC, nikhilpatne commented
Thanks @phospi and @rickmendes,  I have updated changelog fragment for the same

2020-11-09 15:13 UTC, tremble requested changes
In theory this is a breaking change, but in this case I think it's the right thing to do.

2020-11-09 15:13 UTC, tremble commented on changelogs/fragments/283-fixed-ec2_win_password-return-state.yaml
> +  - ec2_win_password returns success when it fails to decode the password.
```suggestion
  - ec2_win_password - return failed if unable to decode the password (https://github.com/ansible-collections/community.aws/issues/142)
```

2020-11-09 15:13 UTC, tremble commented on changelogs/fragments/283-fixed-ec2_win_password-return-state.yaml
> +  - ec2_win_password returns changed state but doesn't change anything.
```suggestion
  - ec2_win_password - on success return state as not changed (https://github.com/ansible-collections/community.aws/issues/145)
```

2020-11-09 16:01 UTC, nikhilpatne commented
Thanks @tremble, Did changes in changelog fragment

2020-11-09 16:22 UTC, tremble approved these changes

2020-11-09 16:24 UTC, merged

2020-11-09 16:24 UTC, tremble commented
We have author and community reviews, code looks sane.  Merging.

@nikhilpatne - Thanks for taking the time to make this PR.
@rickmendes and @phospi - Thanks for taking the time to review the PR.