Fix eip association when both instance id and private ip address are passed
ansible-collections/community.aws pull request #328
Opened 2020-12-10 19:36 UTC by Phoosha

I assume there has recently been a change to the AWS API introducing case sensitivity to the `PrivateIpAddress` parameter of `AssociateAddress`. The `ec2_eip` module uses this parameter in two branches (instance id vs interface id) and only in the instance branch it uses `PrivateIPAddress` (note how it's `P` and not `p`).

This PR also adds a variant of an existing test case to cover the branch that triggered this failure.

## Example

```yaml
- name: Associate an Elastic IP with instance
  ec2_eip:
    device_id: "{{ ec2.instance_ids[0] }}"
    private_ip_address: "{{ ec2.private_ip_address }}"
    state: present
```

This has worked for me for a long time. But when running it today I got this error:
```
The full traceback is:                                                                                                
Traceback (most recent call last):                    
  File "/tmp/ansible_ec2_eip_payload_drz_g_cz/ansible_ec2_eip_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_eip.py", line 249, in associate_ip_and_device
  File "/tmp/ansible_ec2_eip_payload_drz_g_cz/ansible_ec2_eip_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/core.py", line 289, in deciding_wrapper
    return unwrapped(*args, **kwargs)                                                                                 
  File "/usr/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call                                   
    return self._make_api_call(operation_name, kwargs)                                                                
  File "/usr/lib/python3.9/site-packages/botocore/client.py", line 648, in _make_api_call
    request_dict = self._convert_to_request_dict(                                                                     
  File "/usr/lib/python3.9/site-packages/botocore/client.py", line 696, in _convert_to_request_dict                   
    request_dict = self._serializer.serialize_to_request(
  File "/usr/lib/python3.9/site-packages/botocore/validate.py", line 297, in serialize_to_request                      
    raise ParamValidationError(report=report.generate_report())                                                        
botocore.exceptions.ParamValidationError: Parameter validation failed:                                                 
Unknown parameter in input: "PrivateIPAddress", must be one of: AllocationId, InstanceId, PublicIp, AllowReassociation, DryRun, NetworkInterfaceId, PrivateIpAddress
```

2020-12-10 20:19 UTC, tremble requested changes
Hi, the change itself looks good, thanks for updating the test cases too.

Please add a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

2020-12-10 20:22 UTC, tremble commented
Hmm it looks like the changes are failing:

https://app.shippable.com/github/ansible-collections/community.aws/runs/1139/24/tests
```
Traceback (most recent call last):
  File "/tmp/ansible_ec2_instance_payload_rIlC6j/ansible_ec2_instance_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_instance.py", line 1669, in ensure_present
  File "/tmp/ansible_ec2_instance_payload_rIlC6j/ansible_ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py", line 153, in retry_func
    raise e
ClientError: An error occurred (InvalidParameterCombination) when calling the ModifyInstanceAttribute operation: No attributes specified.
```

2020-12-10 20:30 UTC, Phoosha commented
> Hmm it looks like the changes are failing:
> 
> https://app.shippable.com/github/ansible-collections/community.aws/runs/1139/24/tests
> 
> ```
> Traceback (most recent call last):
>   File "/tmp/ansible_ec2_instance_payload_rIlC6j/ansible_ec2_instance_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_instance.py", line 1669, in ensure_present
>   File "/tmp/ansible_ec2_instance_payload_rIlC6j/ansible_ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py", line 153, in retry_func
>     raise e
> ClientError: An error occurred (InvalidParameterCombination) when calling the ModifyInstanceAttribute operation: No attributes specified.
> ```

It seems to me those failures are unrelated. Line 62 is very early in the file where everything is setup for the actual tests. If you haven't seen this before, maybe there has been other changes to AWS APIs. Maybe the `ec2_instance` module needs a fix too or needs to be differently invoked from the tests...

I'll look into the changelog fragment. :+1:

2020-12-10 20:32 UTC, tremble commented
Hi @Phoosha yeah, I'm seeing lots of CI failures related to the Instance APIs, I suspect this is an issue on the AWS side which got combined with a large number of tests going through at the same time.

2020-12-10 21:18 UTC, tremble commented on changelogs/fragments/328-fix-ec2_eip-instance-id-private-ip-address.yml
> +  - ec2_eip - fix eip association by instance id & private ip address due to case-sensitivity of the ``PrivateIpAddress`` parameter (https://github.com/ansible-collections/community.aws/pull/328)
```suggestion
  - ec2_eip - fix eip association by instance id & private ip address due to case-sensitivity of the ``PrivateIpAddress`` parameter (https://github.com/ansible-collections/community.aws/pull/328).
```

2020-12-14 11:27 UTC, tremble commented
The CI issue appears to be related to how ec2_instance finds instances by name, I'm attempting to get it working again.  Once we can run this test suite successfully we should be good to merge this change.

2020-12-15 20:21 UTC, tremble approved these changes

2020-12-15 20:21 UTC, merged

2020-12-15 20:27 UTC, tremble commented
Thank you for your contribution, unfortunately the CI issues we saw from ec2_instance meant we didn't get this merged before 1.3.0, but it shouldn't be too long before the next release.

2020-12-18 16:00 UTC, Phoosha commented
Thanks for keeping me in the loop, Mark. I appreciate it :+1: