ec2_vpc_nacl: add IPv6 support
ansible-collections/community.aws pull request #398
Opened 2021-02-08 14:11 UTC by boutetnico

##### SUMMARY

Add support for IPv6 in `ec2_vpc_nacl`.

This follows an old PR: https://github.com/ansible/ansible/pull/50004.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_vpc_nacl.py

##### ADDITIONAL INFORMATION

I'm not a Python programmer and will be happy to receive feedback on this PR.
I have adapted tests that were previously disabled because they were failing.

```paste below

```

2021-02-27 20:39 UTC, tremble requested changes
Change looks sensible, and this includes integration tests.  1 small thing: please add a changelog fragment.

https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

2021-03-01 08:39 UTC, boutetnico commented
@tremble thanks, I've added a changelog fragment.

2021-03-08 12:46 UTC, tremble approved these changes

2021-03-08 12:47 UTC, merged

2021-03-08 12:48 UTC, tremble commented
@boutetnico thanks for your submission.  This change should be available with the next release (either 1.5.0 or 2.0.0)