rds_instance: map Tags parameters from dict to list on restore_db_instance_from_db_snapshot method
ansible-collections/community.aws pull request #414
Opened 2021-02-15 08:48 UTC by vorotech

##### SUMMARY

Map the `parameters['Tags']` from dict to list with `ansible_dict_to_boto3_tag_list` on `restore_db_instance_from_db_snapshot` method, additionally to existing `create_db_instance` and `create_db_instance_read_replica` methods.

This change will fix the case when db is created from the snaphot and the` tags` parameter is specified on `rds_instance` module.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
rds_instance.py

##### ADDITIONAL INFORMATION

Before the fix, the error is thrown by module:

```
fatal: [rds -> 127.0.0.1]: FAILED! => changed=false 
  boto3_version: 1.11.6
  botocore_version: 1.14.6
  msg: |-
    Unexpected failure for method restore_db_instance_from_db_snapshot with parameters {'Engine': 'MySQL', 'AutoMinorVersionUpgrade': False, 'VpcSecurityGroupIds': ['sg-12345'], 'StorageType': 'gp2', 'DBInstanceIdentifier': 'examplemysql', 'DBInstanceClass': 'db.t3.small', 'DBName': 'examplemysql', 'DBSubnetGroupName': 'subnetgroup', 'MultiAZ': False, 'DBParameterGroupName': 'examplemysql-pg', 'DBSnapshotIdentifier': 'examplemysql-snapshot', 'Tags': {'foo': 'bar', 'env': 'dev'}}: Parameter validation failed:
    Invalid type for parameter Tags, value: {'foo': 'bar', 'env': 'dev'}, type: <class 'dict'>, valid types: <class 'list'>, <class 'tuple'>
```

2021-03-08 10:08 UTC, alinabuzachis commented
Hi @vorotech, thank you for contributing. May you kindly control if you pushed all your changes?

2021-03-11 09:07 UTC, vorotech commented
hi @alinabuzachis 
I'm not too sure what do you referring to...

2021-04-08 18:27 UTC, tremble requested changes
@vorotech I believe @alinabuzachis was trying to politely ask if you've pushed all of your commits.  (the way its phrased looks very much like the way you might politely ask in German)

The rds_instance module isn't the easiest to follow but I believe this is the right change.

Please add a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

Given that the tests currently don't exercise the "creation_source: snapshot" functionality I'd not block on the lack of integration test for this change, but it would be fantastic if you could update our integration tests to exercise this functionality and test setting tags during restoration from a snapshot.  tests/integration/targets/rds_instance/tasks/test_snapshot.yml

2021-04-13 13:47 UTC, tremble commented
@aardbol has confirmed that this fixes the issue (#530):
> Yes, that fixes it. Thanks!

I think we're good to merge this PR

2021-04-13 13:47 UTC, tremble approved these changes

2021-04-13 14:27 UTC, merged

2021-04-13 14:35 UTC, tremble commented
@vorotech Sorry it's taken a while to get this merged.  Many thanks for your submission.  This fix should be available once version 1.5.0 of this collection is released (or 2.0.0 if we skip 1.5.0)