Make "unit" parameter optional and add support for check mode
ansible-collections/community.aws pull request #470
Opened 2021-03-11 04:01 UTC by ichekaldin

##### SUMMARY

boto3 documentation [explicitly suggests omitting this parameter](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch.html#CloudWatch.Client.put_metric_alarm).

Creating an alarm without the "unit" parameter specified fails:

```
- community.aws.ec2_metric_alarm:
    name: My alarm
    description: My description
    namespace: AWS/CertificateManager
    metric: DaysToExpiry
    statistic: Average
    comparison: LessThanOrEqualToThreshold
    threshold: 45
    period: 86400
    evaluation_periods: 1
    dimensions:
      CertificateArn: "arn:aws:acm:us-east-1:123412341234:certificate/example"
    alarm_actions:
      - arn:aws:sns:us-east-1:123412341234:my-sns-topic
    ok_actions:
      - arn:aws:sns:us-east-1:123412341234:my-sns-topic
    treat_missing_data: ignore
    state: present
```

with the following error:

```
Invalid type for parameter Unit, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

Apparently specifying `unit: None` in the example above is not the same as omitting the unit -
it causes the alarm to be in "Insufficient data" state.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_metric_alarm

##### ADDITIONAL INFORMATION

2021-03-11 13:28 UTC, tremble requested changes
Hi @ichekaldin thanks for your PR.

We have some integration tests (tests/integration/targets/ec2_metric_alarm) for this module, it would be good if you could expand these to include testing your latest changes.

While the tests currently run a loop of 
- make-change
- describe-alarms

It would be better (if you're willing) to switch this over to a loop of:
- make-change (check_mode=True) - should return Changed
- make-change (check_mode=False) - should return Changed
- make-change (check_mode=True) - should return Not Changed
- make-change (check_mode=False) - should return Not Changed
for each test

This 4-step loop helps test both idempotency and check_mode

2021-03-11 14:23 UTC, tremble requested changes
Thanks for the initial tests, I'd like to see a test that creates another alarm with no units set.  But once that's in we should be good to go.

2021-03-11 14:41 UTC, tremble commented
The check mode tests seem to be failing:

https://app.shippable.com/github/ansible-collections/community.aws/runs/1818/37/tests

```
                          Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1615473205.9528832-1119-185501734451040/AnsiballZ_ec2_metric_alarm.py", line 126, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1615473205.9528832-1119-185501734451040/AnsiballZ_ec2_metric_alarm.py", line 118, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1615473205.9528832-1119-185501734451040/AnsiballZ_ec2_metric_alarm.py", line 67, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ec2_metric_alarm_payload_zfl19q23/ansible_ec2_metric_alarm_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_metric_alarm.py", line 358, in <module>
  File "/tmp/ansible_ec2_metric_alarm_payload_zfl19q23/ansible_ec2_metric_alarm_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_metric_alarm.py", line 352, in main
  File "/tmp/ansible_ec2_metric_alarm_payload_zfl19q23/ansible_ec2_metric_alarm_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_metric_alarm.py", line 265, in create_metric_alarm
IndexError: list index out of range
```

2021-03-11 21:29 UTC, ichekaldin commented
@tremble It took me a few iterations to get the integrations tests working.

It looks like the PR is now failing the ansible/check test. I see this in the [output](https://dashboard.zuul.ansible.com/t/ansible/build/40e20a6fd2e74aa6ab1dc910b2c98fc8/console):

```
Run command: /usr/bin/python3.6 /root/ansible/test/lib/ansible_test/_data/sanity/validate-modules/validate-modules --format json --arg-spec plugins/modules/aws_acm.py plugins/modules/aws_acm_info.py plugins/modules/aws_api_gateway.py plugins/modules/aws_application_scaling_policy.py plugins/modules/aws_batch_compute_environment.py plugins/modules/aws_batch_job_definition.py plugins/modules/aws_batch_job_queue.py plugins/modules/aws_codebuild.py plugins/modules/aws_codecommit.py plugins/modules/aws_codepipeline.py plugins/modules/aws_config_aggregation_authorization.py plugins/modules/aws_config_aggregator.py plugins/modules/aws_config_delivery_channel.py plugins/modules/aws_config_recorder.py plugins/modules/aws_config_rule.py plugins/modules/aws_direct_connect_confirm_connection.py plugins/modules/aws_direct_connect_connection.py plugins/modules/aws_direct_connect_gateway.py plugins/modules/aws_direct_connect_link_aggregation_group.py plugins/modules/aws_direct_connect_virtual_interface.py plugins/modules/aws_eks_cluster.py plugins/modules/aws_elasticbeanstalk_app.py plugins/modules/aws_glue_connection.py plugins/modules/aws_glue_job.py plugins/modules/aws_inspector_target.py plugins/modules/aws_kms.py plugins/modules/aws_kms_info.py plugins/modules/aws_region_info.py plugins/modules/aws_s3_bucket_info.py plugins/modules/aws_s3_cors.py plugins/modules/aws_secret.py plugins/modules/aws_ses_identity.py plugins/modules/aws_ses_identity_policy.py plugins/modules/aws_ses_rule_set.py plugins/modules/aws_sgw_info.py plugins/modules/aws_ssm_parameter_store.py plugins/modules/aws_step_functions_state_machine.py plugins/modules/aws_step_functions_state_machine_execution.py plugins/modules/aws_waf_condition.py plugins/modules/aws_waf_info.py plugins/modules/aws_waf_rule.py plugins/modules/aws_waf_web_acl.py plugins/modules/cloudformation_exports_info.py plugins/modules/cloudformation_stack_set.py plugins/modules/cloudfront_distribution.py plugins/modules/cloudfront_info.py plugins/modules/cloudfront_invalidation.py plugins/modules/cloudfront_origin_access_identity.py plugins/modules/cloudtrail.py plugins/modules/cloudwatchevent_rule.py plugins/modules/cloudwatchlogs_log_group.py plugins/modules/cloudwatchlogs_log_group_info.py plugins/modules/cloudwatchlogs_log_group_metric_filter.py plugins/modules/data_pipeline.py plugins/modules/dms_endpoint.py plugins/modules/dms_replication_subnet_group.py plugins/modules/dynamodb_table.py plugins/modules/dynamodb_ttl.py plugins/modules/ec2_ami_copy.py plugins/modules/ec2_asg.py plugins/modules/ec2_asg_info.py plugins/modules/ec2_asg_lifecycle_hook.py plugins/modules/ec2_customer_gateway.py plugins/modules/ec2_customer_gateway_info.py plugins/modules/ec2_eip.py plugins/modules/ec2_eip_info.py plugins/modules/ec2_elb.py plugins/modules/ec2_elb_info.py plugins/modules/ec2_instance.py plugins/modules/ec2_instance_info.py plugins/modules/ec2_launch_template.py plugins/modules/ec2_lc.py plugins/modules/ec2_lc_find.py plugins/modules/ec2_lc_info.py plugins/modules/ec2_metric_alarm.py plugins/modules/ec2_placement_group.py plugins/modules/ec2_placement_group_info.py plugins/modules/ec2_scaling_policy.py plugins/modules/ec2_snapshot_copy.py plugins/modules/ec2_transit_gateway.py plugins/modules/ec2_transit_gateway_info.py plugins/modules/ec2_vpc_egress_igw.py plugins/modules/ec2_vpc_endpoint.py plugins/modules/ec2_vpc_endpoint_info.py plugins/modules/ec2_vpc_igw.py plugins/modules/ec2_vpc_igw_info.py plugins/modules/ec2_vpc_nacl.py plugins/modules/ec2_vpc_nacl_info.py plugins/modules/ec2_vpc_nat_gateway.py plugins/modules/ec2_vpc_nat_gateway_info.py plugins/modules/ec2_vpc_peer.py plugins/modules/ec2_vpc_peering_info.py plugins/modules/ec2_vpc_route_table.py plugins/modules/ec2_vpc_route_table_info.py plugins/modules/ec2_vpc_vgw.py plugins/modules/ec2_vpc_vgw_info.py plugins/modules/ec2_vpc_vpn.py plugins/modules/ec2_vpc_vpn_info.py plugins/modules/ec2_win_password.py plugins/modules/ecs_attribute.py plugins/modules/ecs_cluster.py plugins/modules/ecs_ecr.py plugins/modules/ecs_service.py plugins/modules/ecs_service_info.py plugins/modules/ecs_tag.py plugins/modules/ecs_task.py plugins/modules/ecs_taskdefinition.py plugins/modules/ecs_taskdefinition_info.py plugins/modules/efs.py plugins/modules/efs_info.py plugins/modules/elasticache.py plugins/modules/elasticache_info.py plugins/modules/elasticache_parameter_group.py plugins/modules/elasticache_snapshot.py plugins/modules/elasticache_subnet_group.py plugins/modules/elb_application_lb.py plugins/modules/elb_application_lb_info.py plugins/modules/elb_classic_lb.py plugins/modules/elb_classic_lb_info.py plugins/modules/elb_instance.py plugins/modules/elb_network_lb.py plugins/modules/elb_target.py plugins/modules/elb_target_group.py plugins/modules/elb_target_group_info.py plugins/modules/elb_target_info.py plugins/modules/execute_lambda.py plugins/modules/iam.py plugins/modules/iam_cert.py plugins/modules/iam_group.py plugins/modules/iam_managed_policy.py plugins/modules/iam_mfa_device_info.py plugins/modules/iam_password_policy.py plugins/modules/iam_policy.py plugins/modules/iam_policy_info.py plugins/modules/iam_role.py plugins/modules/iam_role_info.py plugins/modules/iam_saml_federation.py plugins/modules/iam_server_certificate_info.py plugins/modules/iam_user.py plugins/modules/iam_user_info.py plugins/modules/kinesis_stream.py plugins/modules/lambda.py plugins/modules/lambda_alias.py plugins/modules/lambda_event.py plugins/modules/lambda_facts.py plugins/modules/lambda_info.py plugins/modules/lambda_policy.py plugins/modules/lightsail.py plugins/modules/rds.py plugins/modules/rds_instance.py plugins/modules/rds_instance_info.py plugins/modules/rds_param_group.py plugins/modules/rds_snapshot.py plugins/modules/rds_snapshot_info.py plugins/modules/rds_subnet_group.py plugins/modules/redshift.py plugins/modules/redshift_cross_region_snapshots.py plugins/modules/redshift_info.py plugins/modules/redshift_subnet_group.py plugins/modules/route53.py plugins/modules/route53_health_check.py plugins/modules/route53_info.py plugins/modules/route53_zone.py plugins/modules/s3_bucket_notification.py plugins/modules/s3_lifecycle.py plugins/modules/s3_logging.py plugins/modules/s3_metrics_configuration.py plugins/modules/s3_sync.py plugins/modules/s3_website.py plugins/modules/sns.py plugins/modules/sns_topic.py plugins/modules/sqs_queue.py plugins/modules/sts_assume_role.py plugins/modules/sts_session_token.py --collection ansible_collections/community/aws --collection-version 1.4.1-dev42
...
Command exited with status 3 after 9.458611965179443 seconds.
ERROR: Found 2 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/aws_secret.py:0:0: no-log-needed: Argument 'secret' in argument_spec could be a secret, though doesn't have `no_log` set
ERROR: plugins/modules/s3_sync.py:0:0: no-log-needed: Argument 'key_prefix' in argument_spec could be a secret, though doesn't have `no_log` set
```

I'm not 100% sure how to move this forward as neither `s3_sync.py` nor `aws_secret.py` are part of this PR. Am I looking at the correct error?

2021-03-12 09:20 UTC, tremble commented
You're looking at the correct error.  There was a recent update to ansible-test's sanity tests which picked up some issues now addressed by #471 given that Shippable's passing.  I wouldn't worry about Zuul right now (we still have some work to do getting things passing in Zuul)

2021-03-12 09:28 UTC, tremble approved these changes
Looks good, thanks for your contribution.  There's a slight tweak that I'll make to the changelog format, which I'm only going to bother with because I want to retrigger the Zuul tests.

2021-03-12 09:28 UTC, tremble commented on changelogs/fragments/470-ec2_metric_alarm-unit-optional.yml
> +  - ec2_metric_alarm - Made ``unit`` parameter optional. Added support for check mode (https://github.com/ansible-collections/community.aws/pull/470).
```suggestion
  - ec2_metric_alarm - Made ``unit`` parameter optional (https://github.com/ansible-collections/community.aws/pull/470).
    - ec2_metric_alarm - Added support for check mode (https://github.com/ansible-collections/community.aws/pull/470).
```

2021-03-12 09:29 UTC, tremble commented on changelogs/fragments/470-ec2_metric_alarm-unit-optional.yml
> +    - ec2_metric_alarm - Added support for check mode (https://github.com/ansible-collections/community.aws/pull/470).
```suggestion
  - ec2_metric_alarm - Made ``unit`` parameter optional (https://github.com/ansible-collections/community.aws/pull/470).
  - ec2_metric_alarm - Added support for check mode (https://github.com/ansible-collections/community.aws/pull/470).
```

2021-03-12 11:08 UTC, merged