rds_instance - fix idempotency when using non-lowercase for preferred_maintenance_window
ansible-collections/community.aws pull request #516
Opened 2021-03-31 12:23 UTC by tremble

##### SUMMARY

Rather than relying on changing the docs (#310) force the day of the week into lowercase so that it matches what AWS returns.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

rds_instance

##### ADDITIONAL INFORMATION

2021-03-31 12:24 UTC, tremble commented
note: tests fail without #515

2021-04-01 13:21 UTC, markuman requested changes
only changelog needs link the the correct pr. otherwise LGTM

2021-04-01 13:21 UTC, markuman commented on changelogs/516-rds_instance-preferred_maintenance_window.yml
> +- rds_instance - convert ``preferred_maintenance_window`` days into lowercase so changed returns properly (https://github.com/ansible-collections/community.aws/pull/515).
Url shows pr 515, but this is 516

2021-04-03 14:22 UTC, tremble commented on changelogs/516-rds_instance-preferred_maintenance_window.yml
> +- rds_instance - convert ``preferred_maintenance_window`` days into lowercase so changed returns properly (https://github.com/ansible-collections/community.aws/pull/515).
```suggestion
- rds_instance - convert ``preferred_maintenance_window`` days into lowercase so changed returns properly (https://github.com/ansible-collections/community.aws/pull/516).
```

2021-04-07 11:51 UTC, tremble commented
Tests also need #531 for the full suite to run.

2021-04-07 12:10 UTC, tremble commented on changelogs/516-rds_instance-preferred_maintenance_window.yml
> +- rds_instance - convert ``preferred_maintenance_window`` days into lowercase so changed returns properly (https://github.com/ansible-collections/community.aws/pull/515).
```suggestion
- rds_instance - convert ``preferred_maintenance_window`` days into lowercase so changed returns properly (https://github.com/ansible-collections/community.aws/pull/516).
```

2021-04-09 12:20 UTC, alinabuzachis approved these changes
LGTM.

2021-04-09 12:44 UTC, merged

2021-04-09 12:44 UTC, tremble commented
Thanks for the reviews @markuman @alinabuzachis