Avoid converting connection_parameter keys to lowercase
ansible-collections/community.aws pull request #518
Opened 2021-04-01 04:09 UTC by ichekaldin

##### SUMMARY

This is a follow to my own PR [#503](https://github.com/ansible-collections/community.aws/pull/503).

This is a cosmetic change that prevents converting keys in connection_parameters dict to lowercase.

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

aws_glue_connection

##### ADDITIONAL INFORMATION

As an example, this:

```
- community.aws.glue_connection:
    name: test-connection
    connection_parameters:
      JDBC_ENFORCE_SSL: "false"
    ...
```

is a valid value, while this:

```
- community.aws.glue_connection:
    name: test-connection
    connection_parameters:
      JDBC_ENFORCE_SSL: "false"
    ...
```

is not.

This PR simply aligns the module output to the expected input.

2021-04-20 22:50 UTC, jillr commented
Thanks for this patch @ichekaldin. However this would be a breaking change, and would need a deprecation period where we would maintain both formats.  

I haven't really used Glue myself, but it looks like the AWS docs use the upper-cased values https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_connection.  I'd like to hear what other Glue users think about this change.  Can the lower-cases values be used as the input for another Glue task?

2021-07-08 16:47 UTC, ichekaldin commented
@jillr from your point of view - is it worth working on this PR further?

2022-07-06 13:01 UTC, tremble commented
@ichekaldin apologies for the delay here.  In my opinion, this is the correct change for the long run, the question is how to 'deprecate' the old key.  We're currently discussing a general cleanup of return values (https://github.com/ansible-collections/amazon.aws/pull/865)

To ensure people have a deprecation cycle available to them the consensus seems to be
- Add a new key with the new value
- Add a deprecation notice that the original key will be updated/removed after 2 years

As such, I'd suggest here is that we add a new return value `raw_connection_parameters` and a deprecation notice.  We'll then just have to wait for the deprecation cycle to complete before changing the original `connection_parameters` value.

2022-07-06 14:05 UTC, tremble requested changes

2022-07-06 14:05 UTC, tremble commented on changelogs/fragments/518-aws_glue_connection-do-not-lowercase-connection-parameters.yml
> +- aws_glue_connection - avoid converting connection_parameters to lowercase (https://github.com/ansible-collections/community.aws/pull/518).
```suggestion
- aws_glue_connection - added new ``raw_connection_parameters`` return key which doesn't snake case the connection parameters (https://github.com/ansible-collections/community.aws/pull/518).
deprecated_features:
- aws_glue_connection - the ``connection_parameters`` return key has been deprecated and will be removed in a release after 2024-06-01, it is being replaced by the ``raw_connection_parameters`` key (https://github.com/ansible-collections/community.aws/pull/518).
```

2022-07-06 14:05 UTC, tremble commented on plugins/modules/glue_connection.py
> +    module.exit_json(changed=changed, **camel_dict_to_snake_dict(glue_connection or {}, ignore_list=['ConnectionProperties']))
```suggestion
    module.exit_json(changed=changed, **camel_dict_to_snake_dict(glue_connection or {}, ignore_list=['RawConnectionProperties']))
```

2022-07-06 15:00 UTC, ichekaldin commented
@tremble Thank you for all the suggestions and edits!

2022-07-06 15:01 UTC, tremble approved these changes

2022-07-06 15:27 UTC, merged