ec2_instance exception handling and client cleanup
ansible-collections/community.aws pull request #526
Opened 2021-04-05 22:17 UTC by jillr

##### SUMMARY
Catch botocore and client errors on all API calls
Pass boto client to functions, rather than creating new clients throughout the code

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
ec2_instance
ec2_instance_info

2021-04-06 00:10 UTC, jillr commented
recheck

2021-04-06 07:08 UTC, tremble commented
recheck

2021-04-06 07:17 UTC, tremble requested changes
Mostly looks good.

2021-04-06 07:17 UTC, tremble commented on plugins/modules/ec2_instance.py
> +        module.fail_json_aws(e, msg="Could not describe instances")
Catching the Error here prevents it falling through the the jittered backoff and being retried it's probably worth  rejigging this a little:

```suggestion
    try:
        results = _describe_instances(ec2, **params)
    except (botocore.exceptions.BotoCoreError, botocore.exceptions.ClientError) as e:
        module.fail_json_aws(e, msg="Could not describe instances")


@AWSRetry.jittered_backoff()
def _describe_instances(ec2, **params):   
    paginator = ec2.get_paginator('describe_instances')
    paginator.paginate(**params).search('Reservations[].Instances[]')
```

2021-04-08 07:53 UTC, tremble commented on plugins/modules/ec2_instance.py
> +    paginator.paginate(**params).search('Reservations[].Instances[]')
```suggestion
    results = paginator.paginate(**params).search('Reservations[].Instances[]')
```

2021-04-08 08:26 UTC, tremble commented on plugins/modules/ec2_instance.py
>      return list(results)
```suggestion
    try:
        results = _describe_instances(ec2, **params)
    except (botocore.exceptions.BotoCoreError, botocore.exceptions.ClientError) as e:
        module.fail_json_aws(e, msg="Could not describe instances")
    return list(results)

@AWSRetry.jittered_backoff()
def _describe_instances(ec2, **params):   
    paginator = ec2.get_paginator('describe_instances')
    return paginator.paginate(**params).search('Reservations[].Instances[]')
```

2021-04-08 08:41 UTC, tremble commented on plugins/modules/ec2_instance.py
> +    paginator = ec2.get_paginator('describe_instances')
```suggestion
    except (botocore.exceptions.BotoCoreError, botocore.exceptions.ClientError) as e:
        module.fail_json_aws(e, msg="Could not describe instances")
    return list(results)


@AWSRetry.jittered_backoff()
def _describe_instances(ec2, **params):
    paginator = ec2.get_paginator('describe_instances')
```

2021-04-08 13:42 UTC, tremble commented
Based on the test failures it looks like we still have a race condition on creation.  Once the tests here pass I'll submit a separate PR to cover it.

2021-04-08 13:43 UTC, tremble approved these changes

2021-04-08 14:54 UTC, merged