Solves 494: added destructor to ssm connection plugin
ansible-collections/community.aws pull request #542
Opened 2021-04-14 09:50 UTC by Chilinot

##### SUMMARY
Fixes #494

Adds destructor to the SSM connection plugin to ensure connections are properly cleaned up after usage.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
SSM connection plugin

2021-04-14 10:05 UTC, tremble requested changes
Hi @Chilinot,

Thanks for taking the time to dig into the issue and open this PR.  If possible please could you add a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

The change itself looks sensible.

2021-04-14 10:06 UTC, tremble commented
@hgrgic you reported also experiencing the issue on #494 if possible please could you test the change in this PR and see if it fixes the issue you're seeing.

2021-04-14 10:59 UTC, hgrgic commented
Hi @tremble  and @Chilinot. Thanks for this update. 

I have tested the proposed fix with my playbooks. Immediately after adding the proposed change I noticed that sessions were terminated properly. At the same time, looking in the AWS Session Manager console, under sessions, at most time I saw only 1 connection being open.

I have repeated the test with the same playbook but before repeating I have removed the proposed change. In this instance I saw more than 20 connection remaining open even after the execution of playbooks has finished. This tells me that the fix is indeed effective.

I recommend merging this PR as soon as possible!

2021-04-14 12:17 UTC, Chilinot commented
@tremble I have now added a changelog fragment as required.

2021-04-14 12:18 UTC, tremble commented on changelogs/fragments/542-ensure-ssm-plugin-terminates-connections.yml
> +  - aws_ssm - Adds destructor to SSM connection plugin to ensure connections are properly cleaned up after usage.
```suggestion
  - aws_ssm - Adds destructor to SSM connection plugin to ensure connections are properly cleaned up after usage (https://github.com/ansible-collections/community.aws/pull/542).
```

2021-04-14 12:21 UTC, tremble approved these changes
LGTM - I'll let the test suites do their thing and hopefully we can get this merged.

2021-04-14 13:05 UTC, tremble commented on changelogs/fragments/542-ensure-ssm-plugin-terminates-connections.yml
> +bug_fixes:
```suggestion
bugfixes:
```

2021-04-14 16:16 UTC, tremble commented
Tests didn't run in zuul for some reason.  Tested locally and they still pass.

2021-04-14 17:44 UTC, merged

2021-04-15 08:46 UTC, hgrgic commented
@tremble What is usually the expected cadence for this merged fix to be included in a release?

2021-04-15 11:12 UTC, tremble commented
Our last release was almost 2 months ago, I'd expect 1.5.0 to land 'soon'.