WIP: Collect arguments for application session stickiness and update docs
ansible-collections/community.aws pull request #548
Opened 2021-04-19 07:15 UTC by heytrav

##### SUMMARY

Additional attributes for elb target group to support application-based session cookies

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

elb_target_group
##### ADDITIONAL INFORMATION

```paste below

```

2021-04-25 13:22 UTC, tremble requested changes
@heytrav thanks for taking the time to open this PR.

The change looks sensible and matches with the upstream docs.  Please would you add a changelog entry and the "version_added" changes.

https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

2021-04-25 13:22 UTC, tremble commented on plugins/modules/elb_target_group.py
> +    type: int
```suggestion
    type: int
    version_added: 1.5.0
```

2021-04-25 13:22 UTC, tremble commented on plugins/modules/elb_target_group.py
> +    type: str
```suggestion
    type: str
    version_added: 1.5.0
```

2021-04-26 00:29 UTC, heytrav commented on plugins/modules/elb_target_group.py
> +    type: str
Ok, added

2021-04-26 07:09 UTC, tremble approved these changes

2021-04-26 07:13 UTC, tremble commented on plugins/modules/elb_target_group.py
> +        C(app_cookie).
```suggestion
      - The name of the application cookie. Required if I(stickiness_type=app_cookie).
```

Just a niggle I'll merge, but we use `I(...)` for parameters and `C(...)` for values.

2021-04-26 07:13 UTC, tremble commented on plugins/modules/elb_target_group.py
> +      - C(lb_cookie), C(app_cookie) or C(source_ip)
```suggestion
      - Valid values are C(lb_cookie), C(app_cookie) or C(source_ip)
```

2021-04-26 09:45 UTC, merged