Updating documentation for changes in PR #39
ansible-collections/community.aws pull request #674
Opened 2021-08-05 14:37 UTC by landphil

https://github.com/ansible-collections/community.aws/pull/39

Adding `s3_origin_config` to docs in parameters and return values

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-08-09 19:19 UTC, markuman commented
@landphil thx for your first PR to this collection.  
You need also `changelog/fragments/` file. When you add it, it will automatically kick the CI again, because the failed task is not related with your PR.

2021-08-10 13:40 UTC, tremble requested changes
niggles

2021-08-10 13:40 UTC, tremble commented on plugins/modules/cloudfront_distribution.py
> +          description: Specify origin access identity for S3 origins
```suggestion
          description: Specify origin access identity for S3 origins.
```

2021-08-10 13:40 UTC, tremble commented on plugins/modules/cloudfront_distribution.py
> +              description: Existing origin access identity in the format C(origin-access-identity/cloudfront/OID_ID)
```suggestion
              description: Existing origin access identity in the format C(origin-access-identity/cloudfront/OID_ID).
```

2021-08-10 13:40 UTC, tremble commented on plugins/modules/cloudfront_distribution.py
> +              description: The origin access id as a path
```suggestion
              description: The origin access id as a path.
```

2021-08-10 13:41 UTC, tremble approved these changes

2021-08-11 14:27 UTC, landphil commented
> @landphil thx for your first PR to this collection.
> You need also `changelog/fragments/` file. When you add it, it will automatically kick the CI again, because the failed task is not related with your PR.
Hi Markus- The developer docs say you don't add a changelog entry for documentation changes:

https://docs.ansible.com/ansible/latest/community/development_process.html#making-your-pr-merge-worthy

I can get one in there if you really want it, though.

Thanks all for getting this merged- I was about 10 minutes into modifying the module to add the functionality I needed, when I realized it was already there and undocumented!

2021-08-11 14:32 UTC, tremble commented
For a pure docs update I wouldn't worry about the changelog.  I've kicked off the final test/merge workflow.

Thanks for your contribution.

2021-08-12 14:31 UTC, alinabuzachis commented
recheck

2021-08-13 12:43 UTC, tremble commented
recheck

2021-08-13 16:25 UTC, merged