AWS SSM connection: Add ability to specify S3 addressing style
ansible-collections/community.aws pull request #786
Opened 2021-10-29 13:30 UTC by timburnet-systematica

This is useful for newly created buckets in combination with private s3 endpoints.

##### SUMMARY
This is useful for newly created buckets in combination with private s3 endpoints where the current code just breaks

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
aws_ssm

2022-01-09 09:33 UTC, gillg commented
@markuman possible to merge this PR with https://github.com/ansible-collections/community.aws/pull/854 ?
@james-masson can you add a changlog fragment, version add 3.0.0 in the doc part, and add possible values like "auto" in the doc part ?

2022-01-09 13:32 UTC, gillg requested changes

2022-01-09 13:32 UTC, gillg commented on plugins/connection/aws_ssm.py
> +    - name: ansible_aws_ssm_s3_addressing_style
Missing 
```yaml
version_added: 3.0.0
choices:
  - auto
  - virtual
```

2022-03-07 06:04 UTC, Hokwang commented
please take care this PR. I think #705 should not close yet.

2022-05-09 23:27 UTC, jatorcasso commented
recheck

2022-12-30 13:14 UTC, adsanz commented
Note: this issue fixes #637 (which appears closed, but actually this PR is the fix) I've implemented the PR on my collection install and test it against a newly created bucket (less than 1 month old) which had the same issue as described by #637 and it worked. Is there any chance this gets merged soon? As anybody with a newly created bucket for SSM connections is probably going to face the same problem.

2023-01-20 15:15 UTC, tremble commented
Thanks for taking the time to submit this PR.  It appears to have stalled out, and because I can't push to the branch I can't revive this.

The work has been revived in #1633 and will hopefully be available in 5.2.0 (Real Soon Now, honest)

2023-01-20 15:15 UTC, closed without merging