Prepare for community.aws release 3.0.0
ansible-collections/community.aws pull request #848
Opened 2022-01-06 07:02 UTC by markuman

##### SUMMARY

next major release

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

everything

2022-01-06 07:27 UTC, markuman commented
recheck

2022-01-06 11:12 UTC, markuman commented
recheck

2022-01-06 17:30 UTC, markuman commented
recheck

2022-01-06 19:07 UTC, markuman commented
recheck

2022-01-07 08:21 UTC, alinabuzachis requested changes
I guess you also have to update the amazon.aws version here https://github.com/ansible-collections/community.aws/blob/main/tests/requirements.yml#L2

I guess docs update is missing. Did you generate the docs using [`collection_prep` repo](https://github.com/alinabuzachis/collection_prep)?

2022-01-07 08:21 UTC, alinabuzachis commented on galaxy.yml
>  namespace: community
I guess we also have to update `amazon.aws` version in dependencies to `3.0.0`.

2022-01-07 10:23 UTC, alinabuzachis approved these changes

2022-01-07 12:02 UTC, markuman commented
recheck

2022-01-07 15:19 UTC, tremble submitted a review, later dismissed
Sorry about the delayed response.  Mostly looks good ec2_elb was deprecated and should probably go away.

2022-01-07 15:19 UTC, tremble commented on meta/runtime.yml
>        redirect: community.aws.elb_instance
```suggestion
```

2022-01-08 19:44 UTC, markuman commented
recheck

2022-01-09 08:51 UTC, markuman commented
recheck

2022-01-10 09:37 UTC, alinabuzachis approved these changes

2022-01-10 21:41 UTC, jillr approved these changes

2022-01-11 18:38 UTC, markuman commented
The gating process is stalling...  
cc @goneri

2022-01-12 11:01 UTC, alinabuzachis commented
@markuman I throw it there. Could it be because there seem to be ** Changes requested**? Have you tried to dismiss this?

2022-01-12 11:04 UTC, markuman commented
> @markuman I throw it there. Could it be because there seems to be **Changes requested**? Have you tried to dismiss this?

I'll try

2022-01-12 11:33 UTC, merged