Move some shared logic in module utils/sns
ansible-collections/community.aws pull request #879
Opened 2022-01-21 10:42 UTC by alinabuzachis

##### SUMMARY

Move some shared logic in module utils/sns

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

sns_topic
sns
sns_topic_info

2022-01-21 10:58 UTC, tremble requested changes
I'm running a slightly stricter set of pylint tests locally that I think are worth fixing:
```
ERROR: plugins/module_utils/sns.py:125:0: missing-final-newline: Final newline missing
ERROR: plugins/modules/sns_topic.py:287:0: unused-import: Unused import re
ERROR: plugins/modules/sns_topic.py:288:0: unused-import: Unused import copy
```

2022-01-21 10:59 UTC, tremble commented
(but otherwise looks good)
Thanks for this @alinabuzachis.

2022-01-21 11:34 UTC, tremble approved these changes

2022-01-21 13:42 UTC, marknet15 commented on plugins/module_utils/sns.py
> +    return paginator.paginate().build_full_result()['Subscriptions']
Is it worth combining these in a single function with a param input? for example:
https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/cloudfront_info.py#L319

Might make it easier then if any different paginators get used later

2022-01-28 09:09 UTC, markuman approved these changes

2022-01-28 09:10 UTC, markuman commented
recheck

2022-02-02 10:41 UTC, merged