fix: ansible kinesis stream paginated shards bug
ansible-collections/community.aws pull request #93
Opened 2020-06-09 16:11 UTC by sidpatel13

##### SUMMARY
"Fixes #92"

It looks like `has_more_shards` isn't really used other than for the purposes of this while loop so it is safe to set `ExclusiveStartShardId` to the last shard and pass those params at the next call of the while loop which subsequently sets `has_more_shards` to False. Otherwise, due to a kinesis stream having > 100 shards, `has_more_shards` will always be True making us stuck in this while loop and we'll get timeouts.

##### ISSUE TYPE
- Bugfix Pull Request

2020-06-16 14:59 UTC, sidpatel13 commented on plugins/modules/kinesis_stream.py
> +                if has_more_shards:
ran into an index out of range error when creating new kinesis streams that don't have shards assigned to them yet so added in this check

2020-08-20 07:33 UTC, tremble requested changes
Hi @sidpatel13 

Thanks for taking the time to submit the issue and this patch.

I think this change might work, we currently have a pending PR to add some integration tests for kinesis_stream ( https://github.com/ansible-collections/community.aws/pull/42 ) that I'd like to get in place before we merge this.

In the mean time if possible please would you add a changelog fragment to your PR: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

Given the number of shards required to trigger this I'm not sure we can practically test this properly without delving into the realms of unit tests and I'm not a big fan of unit tests for modules so I'm inclined to wave that requirement.

2020-08-24 19:28 UTC, tremble approved these changes
LGTM, I'm going to wait on getting the integration tests in place before merging.

2020-08-31 21:55 UTC, sidpatel13 commented
@ansibullbot rebased!

2020-10-08 19:22 UTC, tremble commented
Sorry it took so long, We've got the initial test suite in now and I've triggered a run.  I'll manually run through the results (there are some known bugs) and then we can get this merged.

2020-12-01 16:03 UTC, merged

2020-12-01 16:03 UTC, tremble commented
Sorry this took so long to get merged.